# Generated by Django 3.2.3 on 2021-07-21 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Primeflix', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titulo',
            name='tipo',
        ),
    ]
