# Generated by Django 3.2.3 on 2021-07-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Primeflix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='datalancamento',
            field=models.CharField(max_length=10, verbose_name='Data de Lançamento'),
        ),
        migrations.AlterField(
            model_name='titulo',
            name='sinopse',
            field=models.TextField(max_length=1000, verbose_name='Sinopse'),
        ),
    ]
