# Generated by Django 3.2.3 on 2021-07-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Primeflix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='anofim',
            field=models.IntegerField(null=True, verbose_name='AnoFim'),
        ),
        migrations.AlterField(
            model_name='titulo',
            name='ano',
            field=models.IntegerField(verbose_name='Sinopse'),
        ),
    ]
