# Generated by Django 3.2.3 on 2021-07-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Primeflix', '0003_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='num_temporada',
            field=models.IntegerField(null=True, verbose_name='Temporadas'),
        ),
    ]
