# Generated by Django 3.2.3 on 2021-07-26 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Primeflix', '0004_serie_num_temporada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('idgenero', models.AutoField(primary_key=True, serialize=False, verbose_name='idgenero')),
                ('genero', models.CharField(max_length=20, verbose_name='Genero')),
            ],
        ),
        migrations.CreateModel(
            name='Possui',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_genero', models.ForeignKey(db_column='idgenero', on_delete=django.db.models.deletion.CASCADE, to='Primeflix.genero')),
                ('fk_titulo', models.ForeignKey(db_column='idtitulo', on_delete=django.db.models.deletion.CASCADE, to='Primeflix.titulo')),
            ],
        ),
    ]
